// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/core/cache.proto
// Protobuf Java Version: 4.26.1

package com.teneasyChat.api.core;

public final class Cache {
  private Cache() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Cache.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetReqV1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.core.GetReqV1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 key = 1;</code>
     * @return The key.
     */
    long getKey();

    /**
     * <pre>
     * 执行次数
     * </pre>
     *
     * <code>uint64 exec_num = 2;</code>
     * @return The execNum.
     */
    long getExecNum();

    /**
     * <pre>
     * 协程数量
     * </pre>
     *
     * <code>uint64 c_num = 3;</code>
     * @return The cNum.
     */
    long getCNum();
  }
  /**
   * <pre>
   * get request
   * </pre>
   *
   * Protobuf type {@code api.core.GetReqV1}
   */
  public static final class GetReqV1 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:api.core.GetReqV1)
      GetReqV1OrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        GetReqV1.class.getName());
    }
    // Use GetReqV1.newBuilder() to construct.
    private GetReqV1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetReqV1() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.core.Cache.internal_static_api_core_GetReqV1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.core.Cache.internal_static_api_core_GetReqV1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.core.Cache.GetReqV1.class, com.teneasyChat.api.core.Cache.GetReqV1.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private long key_ = 0L;
    /**
     * <code>uint64 key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public long getKey() {
      return key_;
    }

    public static final int EXEC_NUM_FIELD_NUMBER = 2;
    private long execNum_ = 0L;
    /**
     * <pre>
     * 执行次数
     * </pre>
     *
     * <code>uint64 exec_num = 2;</code>
     * @return The execNum.
     */
    @java.lang.Override
    public long getExecNum() {
      return execNum_;
    }

    public static final int C_NUM_FIELD_NUMBER = 3;
    private long cNum_ = 0L;
    /**
     * <pre>
     * 协程数量
     * </pre>
     *
     * <code>uint64 c_num = 3;</code>
     * @return The cNum.
     */
    @java.lang.Override
    public long getCNum() {
      return cNum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (key_ != 0L) {
        output.writeUInt64(1, key_);
      }
      if (execNum_ != 0L) {
        output.writeUInt64(2, execNum_);
      }
      if (cNum_ != 0L) {
        output.writeUInt64(3, cNum_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (key_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, key_);
      }
      if (execNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, execNum_);
      }
      if (cNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, cNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.core.Cache.GetReqV1)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.core.Cache.GetReqV1 other = (com.teneasyChat.api.core.Cache.GetReqV1) obj;

      if (getKey()
          != other.getKey()) return false;
      if (getExecNum()
          != other.getExecNum()) return false;
      if (getCNum()
          != other.getCNum()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getKey());
      hash = (37 * hash) + EXEC_NUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExecNum());
      hash = (37 * hash) + C_NUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCNum());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.core.Cache.GetReqV1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.Cache.GetReqV1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.GetReqV1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.Cache.GetReqV1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.GetReqV1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.Cache.GetReqV1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.GetReqV1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.Cache.GetReqV1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.teneasyChat.api.core.Cache.GetReqV1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.teneasyChat.api.core.Cache.GetReqV1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.GetReqV1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.Cache.GetReqV1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.core.Cache.GetReqV1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * get request
     * </pre>
     *
     * Protobuf type {@code api.core.GetReqV1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.core.GetReqV1)
        com.teneasyChat.api.core.Cache.GetReqV1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.core.Cache.internal_static_api_core_GetReqV1_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.core.Cache.internal_static_api_core_GetReqV1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.core.Cache.GetReqV1.class, com.teneasyChat.api.core.Cache.GetReqV1.Builder.class);
      }

      // Construct using com.teneasyChat.api.core.Cache.GetReqV1.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = 0L;
        execNum_ = 0L;
        cNum_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.core.Cache.internal_static_api_core_GetReqV1_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.Cache.GetReqV1 getDefaultInstanceForType() {
        return com.teneasyChat.api.core.Cache.GetReqV1.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.core.Cache.GetReqV1 build() {
        com.teneasyChat.api.core.Cache.GetReqV1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.Cache.GetReqV1 buildPartial() {
        com.teneasyChat.api.core.Cache.GetReqV1 result = new com.teneasyChat.api.core.Cache.GetReqV1(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.api.core.Cache.GetReqV1 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.execNum_ = execNum_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.cNum_ = cNum_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.core.Cache.GetReqV1) {
          return mergeFrom((com.teneasyChat.api.core.Cache.GetReqV1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.core.Cache.GetReqV1 other) {
        if (other == com.teneasyChat.api.core.Cache.GetReqV1.getDefaultInstance()) return this;
        if (other.getKey() != 0L) {
          setKey(other.getKey());
        }
        if (other.getExecNum() != 0L) {
          setExecNum(other.getExecNum());
        }
        if (other.getCNum() != 0L) {
          setCNum(other.getCNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                key_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                execNum_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                cNum_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long key_ ;
      /**
       * <code>uint64 key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public long getKey() {
        return key_;
      }
      /**
       * <code>uint64 key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(long value) {

        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = 0L;
        onChanged();
        return this;
      }

      private long execNum_ ;
      /**
       * <pre>
       * 执行次数
       * </pre>
       *
       * <code>uint64 exec_num = 2;</code>
       * @return The execNum.
       */
      @java.lang.Override
      public long getExecNum() {
        return execNum_;
      }
      /**
       * <pre>
       * 执行次数
       * </pre>
       *
       * <code>uint64 exec_num = 2;</code>
       * @param value The execNum to set.
       * @return This builder for chaining.
       */
      public Builder setExecNum(long value) {

        execNum_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 执行次数
       * </pre>
       *
       * <code>uint64 exec_num = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        execNum_ = 0L;
        onChanged();
        return this;
      }

      private long cNum_ ;
      /**
       * <pre>
       * 协程数量
       * </pre>
       *
       * <code>uint64 c_num = 3;</code>
       * @return The cNum.
       */
      @java.lang.Override
      public long getCNum() {
        return cNum_;
      }
      /**
       * <pre>
       * 协程数量
       * </pre>
       *
       * <code>uint64 c_num = 3;</code>
       * @param value The cNum to set.
       * @return This builder for chaining.
       */
      public Builder setCNum(long value) {

        cNum_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协程数量
       * </pre>
       *
       * <code>uint64 c_num = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cNum_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.core.GetReqV1)
    }

    // @@protoc_insertion_point(class_scope:api.core.GetReqV1)
    private static final com.teneasyChat.api.core.Cache.GetReqV1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.core.Cache.GetReqV1();
    }

    public static com.teneasyChat.api.core.Cache.GetReqV1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetReqV1>
        PARSER = new com.google.protobuf.AbstractParser<GetReqV1>() {
      @java.lang.Override
      public GetReqV1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetReqV1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetReqV1> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.core.Cache.GetReqV1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetRespV1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.core.GetRespV1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 key = 1;</code>
     * @return The key.
     */
    long getKey();

    /**
     * <pre>
     * 执行次数
     * </pre>
     *
     * <code>uint64 exec_num = 2;</code>
     * @return The execNum.
     */
    long getExecNum();

    /**
     * <code>uint64 value = 3;</code>
     * @return The value.
     */
    long getValue();

    /**
     * <code>uint64 value_time = 4;</code>
     * @return The valueTime.
     */
    long getValueTime();

    /**
     * <pre>
     * 执行时间
     * </pre>
     *
     * <code>int64 exec_mil_time = 5;</code>
     * @return The execMilTime.
     */
    long getExecMilTime();
  }
  /**
   * <pre>
   * get response
   * </pre>
   *
   * Protobuf type {@code api.core.GetRespV1}
   */
  public static final class GetRespV1 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:api.core.GetRespV1)
      GetRespV1OrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        GetRespV1.class.getName());
    }
    // Use GetRespV1.newBuilder() to construct.
    private GetRespV1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetRespV1() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.core.Cache.internal_static_api_core_GetRespV1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.core.Cache.internal_static_api_core_GetRespV1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.core.Cache.GetRespV1.class, com.teneasyChat.api.core.Cache.GetRespV1.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private long key_ = 0L;
    /**
     * <code>uint64 key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public long getKey() {
      return key_;
    }

    public static final int EXEC_NUM_FIELD_NUMBER = 2;
    private long execNum_ = 0L;
    /**
     * <pre>
     * 执行次数
     * </pre>
     *
     * <code>uint64 exec_num = 2;</code>
     * @return The execNum.
     */
    @java.lang.Override
    public long getExecNum() {
      return execNum_;
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private long value_ = 0L;
    /**
     * <code>uint64 value = 3;</code>
     * @return The value.
     */
    @java.lang.Override
    public long getValue() {
      return value_;
    }

    public static final int VALUE_TIME_FIELD_NUMBER = 4;
    private long valueTime_ = 0L;
    /**
     * <code>uint64 value_time = 4;</code>
     * @return The valueTime.
     */
    @java.lang.Override
    public long getValueTime() {
      return valueTime_;
    }

    public static final int EXEC_MIL_TIME_FIELD_NUMBER = 5;
    private long execMilTime_ = 0L;
    /**
     * <pre>
     * 执行时间
     * </pre>
     *
     * <code>int64 exec_mil_time = 5;</code>
     * @return The execMilTime.
     */
    @java.lang.Override
    public long getExecMilTime() {
      return execMilTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (key_ != 0L) {
        output.writeUInt64(1, key_);
      }
      if (execNum_ != 0L) {
        output.writeUInt64(2, execNum_);
      }
      if (value_ != 0L) {
        output.writeUInt64(3, value_);
      }
      if (valueTime_ != 0L) {
        output.writeUInt64(4, valueTime_);
      }
      if (execMilTime_ != 0L) {
        output.writeInt64(5, execMilTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (key_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, key_);
      }
      if (execNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, execNum_);
      }
      if (value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, value_);
      }
      if (valueTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, valueTime_);
      }
      if (execMilTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, execMilTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.core.Cache.GetRespV1)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.core.Cache.GetRespV1 other = (com.teneasyChat.api.core.Cache.GetRespV1) obj;

      if (getKey()
          != other.getKey()) return false;
      if (getExecNum()
          != other.getExecNum()) return false;
      if (getValue()
          != other.getValue()) return false;
      if (getValueTime()
          != other.getValueTime()) return false;
      if (getExecMilTime()
          != other.getExecMilTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getKey());
      hash = (37 * hash) + EXEC_NUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExecNum());
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValue());
      hash = (37 * hash) + VALUE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValueTime());
      hash = (37 * hash) + EXEC_MIL_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExecMilTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.core.Cache.GetRespV1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.Cache.GetRespV1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.GetRespV1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.Cache.GetRespV1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.GetRespV1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.Cache.GetRespV1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.GetRespV1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.Cache.GetRespV1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.teneasyChat.api.core.Cache.GetRespV1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.teneasyChat.api.core.Cache.GetRespV1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.GetRespV1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.Cache.GetRespV1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.core.Cache.GetRespV1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * get response
     * </pre>
     *
     * Protobuf type {@code api.core.GetRespV1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.core.GetRespV1)
        com.teneasyChat.api.core.Cache.GetRespV1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.core.Cache.internal_static_api_core_GetRespV1_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.core.Cache.internal_static_api_core_GetRespV1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.core.Cache.GetRespV1.class, com.teneasyChat.api.core.Cache.GetRespV1.Builder.class);
      }

      // Construct using com.teneasyChat.api.core.Cache.GetRespV1.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = 0L;
        execNum_ = 0L;
        value_ = 0L;
        valueTime_ = 0L;
        execMilTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.core.Cache.internal_static_api_core_GetRespV1_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.Cache.GetRespV1 getDefaultInstanceForType() {
        return com.teneasyChat.api.core.Cache.GetRespV1.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.core.Cache.GetRespV1 build() {
        com.teneasyChat.api.core.Cache.GetRespV1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.Cache.GetRespV1 buildPartial() {
        com.teneasyChat.api.core.Cache.GetRespV1 result = new com.teneasyChat.api.core.Cache.GetRespV1(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.api.core.Cache.GetRespV1 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.execNum_ = execNum_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.valueTime_ = valueTime_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.execMilTime_ = execMilTime_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.core.Cache.GetRespV1) {
          return mergeFrom((com.teneasyChat.api.core.Cache.GetRespV1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.core.Cache.GetRespV1 other) {
        if (other == com.teneasyChat.api.core.Cache.GetRespV1.getDefaultInstance()) return this;
        if (other.getKey() != 0L) {
          setKey(other.getKey());
        }
        if (other.getExecNum() != 0L) {
          setExecNum(other.getExecNum());
        }
        if (other.getValue() != 0L) {
          setValue(other.getValue());
        }
        if (other.getValueTime() != 0L) {
          setValueTime(other.getValueTime());
        }
        if (other.getExecMilTime() != 0L) {
          setExecMilTime(other.getExecMilTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                key_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                execNum_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                value_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                valueTime_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                execMilTime_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long key_ ;
      /**
       * <code>uint64 key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public long getKey() {
        return key_;
      }
      /**
       * <code>uint64 key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(long value) {

        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = 0L;
        onChanged();
        return this;
      }

      private long execNum_ ;
      /**
       * <pre>
       * 执行次数
       * </pre>
       *
       * <code>uint64 exec_num = 2;</code>
       * @return The execNum.
       */
      @java.lang.Override
      public long getExecNum() {
        return execNum_;
      }
      /**
       * <pre>
       * 执行次数
       * </pre>
       *
       * <code>uint64 exec_num = 2;</code>
       * @param value The execNum to set.
       * @return This builder for chaining.
       */
      public Builder setExecNum(long value) {

        execNum_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 执行次数
       * </pre>
       *
       * <code>uint64 exec_num = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        execNum_ = 0L;
        onChanged();
        return this;
      }

      private long value_ ;
      /**
       * <code>uint64 value = 3;</code>
       * @return The value.
       */
      @java.lang.Override
      public long getValue() {
        return value_;
      }
      /**
       * <code>uint64 value = 3;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(long value) {

        value_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = 0L;
        onChanged();
        return this;
      }

      private long valueTime_ ;
      /**
       * <code>uint64 value_time = 4;</code>
       * @return The valueTime.
       */
      @java.lang.Override
      public long getValueTime() {
        return valueTime_;
      }
      /**
       * <code>uint64 value_time = 4;</code>
       * @param value The valueTime to set.
       * @return This builder for chaining.
       */
      public Builder setValueTime(long value) {

        valueTime_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 value_time = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearValueTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        valueTime_ = 0L;
        onChanged();
        return this;
      }

      private long execMilTime_ ;
      /**
       * <pre>
       * 执行时间
       * </pre>
       *
       * <code>int64 exec_mil_time = 5;</code>
       * @return The execMilTime.
       */
      @java.lang.Override
      public long getExecMilTime() {
        return execMilTime_;
      }
      /**
       * <pre>
       * 执行时间
       * </pre>
       *
       * <code>int64 exec_mil_time = 5;</code>
       * @param value The execMilTime to set.
       * @return This builder for chaining.
       */
      public Builder setExecMilTime(long value) {

        execMilTime_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 执行时间
       * </pre>
       *
       * <code>int64 exec_mil_time = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecMilTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        execMilTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.core.GetRespV1)
    }

    // @@protoc_insertion_point(class_scope:api.core.GetRespV1)
    private static final com.teneasyChat.api.core.Cache.GetRespV1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.core.Cache.GetRespV1();
    }

    public static com.teneasyChat.api.core.Cache.GetRespV1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetRespV1>
        PARSER = new com.google.protobuf.AbstractParser<GetRespV1>() {
      @java.lang.Override
      public GetRespV1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetRespV1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetRespV1> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.core.Cache.GetRespV1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SetReqV1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.core.SetReqV1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 key = 1;</code>
     * @return The key.
     */
    long getKey();

    /**
     * <code>uint64 value = 2;</code>
     * @return The value.
     */
    long getValue();

    /**
     * <pre>
     * 执行次数
     * </pre>
     *
     * <code>uint64 exec_num = 3;</code>
     * @return The execNum.
     */
    long getExecNum();

    /**
     * <pre>
     * 协程数量
     * </pre>
     *
     * <code>uint64 c_num = 4;</code>
     * @return The cNum.
     */
    long getCNum();
  }
  /**
   * Protobuf type {@code api.core.SetReqV1}
   */
  public static final class SetReqV1 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:api.core.SetReqV1)
      SetReqV1OrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        SetReqV1.class.getName());
    }
    // Use SetReqV1.newBuilder() to construct.
    private SetReqV1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SetReqV1() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.core.Cache.internal_static_api_core_SetReqV1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.core.Cache.internal_static_api_core_SetReqV1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.core.Cache.SetReqV1.class, com.teneasyChat.api.core.Cache.SetReqV1.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private long key_ = 0L;
    /**
     * <code>uint64 key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public long getKey() {
      return key_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private long value_ = 0L;
    /**
     * <code>uint64 value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public long getValue() {
      return value_;
    }

    public static final int EXEC_NUM_FIELD_NUMBER = 3;
    private long execNum_ = 0L;
    /**
     * <pre>
     * 执行次数
     * </pre>
     *
     * <code>uint64 exec_num = 3;</code>
     * @return The execNum.
     */
    @java.lang.Override
    public long getExecNum() {
      return execNum_;
    }

    public static final int C_NUM_FIELD_NUMBER = 4;
    private long cNum_ = 0L;
    /**
     * <pre>
     * 协程数量
     * </pre>
     *
     * <code>uint64 c_num = 4;</code>
     * @return The cNum.
     */
    @java.lang.Override
    public long getCNum() {
      return cNum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (key_ != 0L) {
        output.writeUInt64(1, key_);
      }
      if (value_ != 0L) {
        output.writeUInt64(2, value_);
      }
      if (execNum_ != 0L) {
        output.writeUInt64(3, execNum_);
      }
      if (cNum_ != 0L) {
        output.writeUInt64(4, cNum_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (key_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, key_);
      }
      if (value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, value_);
      }
      if (execNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, execNum_);
      }
      if (cNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, cNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.core.Cache.SetReqV1)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.core.Cache.SetReqV1 other = (com.teneasyChat.api.core.Cache.SetReqV1) obj;

      if (getKey()
          != other.getKey()) return false;
      if (getValue()
          != other.getValue()) return false;
      if (getExecNum()
          != other.getExecNum()) return false;
      if (getCNum()
          != other.getCNum()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getKey());
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValue());
      hash = (37 * hash) + EXEC_NUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExecNum());
      hash = (37 * hash) + C_NUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCNum());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.core.Cache.SetReqV1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.Cache.SetReqV1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.SetReqV1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.Cache.SetReqV1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.SetReqV1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.Cache.SetReqV1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.SetReqV1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.Cache.SetReqV1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.teneasyChat.api.core.Cache.SetReqV1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.teneasyChat.api.core.Cache.SetReqV1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.SetReqV1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.Cache.SetReqV1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.core.Cache.SetReqV1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code api.core.SetReqV1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.core.SetReqV1)
        com.teneasyChat.api.core.Cache.SetReqV1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.core.Cache.internal_static_api_core_SetReqV1_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.core.Cache.internal_static_api_core_SetReqV1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.core.Cache.SetReqV1.class, com.teneasyChat.api.core.Cache.SetReqV1.Builder.class);
      }

      // Construct using com.teneasyChat.api.core.Cache.SetReqV1.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = 0L;
        value_ = 0L;
        execNum_ = 0L;
        cNum_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.core.Cache.internal_static_api_core_SetReqV1_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.Cache.SetReqV1 getDefaultInstanceForType() {
        return com.teneasyChat.api.core.Cache.SetReqV1.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.core.Cache.SetReqV1 build() {
        com.teneasyChat.api.core.Cache.SetReqV1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.Cache.SetReqV1 buildPartial() {
        com.teneasyChat.api.core.Cache.SetReqV1 result = new com.teneasyChat.api.core.Cache.SetReqV1(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.api.core.Cache.SetReqV1 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.execNum_ = execNum_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.cNum_ = cNum_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.core.Cache.SetReqV1) {
          return mergeFrom((com.teneasyChat.api.core.Cache.SetReqV1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.core.Cache.SetReqV1 other) {
        if (other == com.teneasyChat.api.core.Cache.SetReqV1.getDefaultInstance()) return this;
        if (other.getKey() != 0L) {
          setKey(other.getKey());
        }
        if (other.getValue() != 0L) {
          setValue(other.getValue());
        }
        if (other.getExecNum() != 0L) {
          setExecNum(other.getExecNum());
        }
        if (other.getCNum() != 0L) {
          setCNum(other.getCNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                key_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                value_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                execNum_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                cNum_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long key_ ;
      /**
       * <code>uint64 key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public long getKey() {
        return key_;
      }
      /**
       * <code>uint64 key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(long value) {

        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = 0L;
        onChanged();
        return this;
      }

      private long value_ ;
      /**
       * <code>uint64 value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public long getValue() {
        return value_;
      }
      /**
       * <code>uint64 value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(long value) {

        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0L;
        onChanged();
        return this;
      }

      private long execNum_ ;
      /**
       * <pre>
       * 执行次数
       * </pre>
       *
       * <code>uint64 exec_num = 3;</code>
       * @return The execNum.
       */
      @java.lang.Override
      public long getExecNum() {
        return execNum_;
      }
      /**
       * <pre>
       * 执行次数
       * </pre>
       *
       * <code>uint64 exec_num = 3;</code>
       * @param value The execNum to set.
       * @return This builder for chaining.
       */
      public Builder setExecNum(long value) {

        execNum_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 执行次数
       * </pre>
       *
       * <code>uint64 exec_num = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        execNum_ = 0L;
        onChanged();
        return this;
      }

      private long cNum_ ;
      /**
       * <pre>
       * 协程数量
       * </pre>
       *
       * <code>uint64 c_num = 4;</code>
       * @return The cNum.
       */
      @java.lang.Override
      public long getCNum() {
        return cNum_;
      }
      /**
       * <pre>
       * 协程数量
       * </pre>
       *
       * <code>uint64 c_num = 4;</code>
       * @param value The cNum to set.
       * @return This builder for chaining.
       */
      public Builder setCNum(long value) {

        cNum_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协程数量
       * </pre>
       *
       * <code>uint64 c_num = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cNum_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.core.SetReqV1)
    }

    // @@protoc_insertion_point(class_scope:api.core.SetReqV1)
    private static final com.teneasyChat.api.core.Cache.SetReqV1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.core.Cache.SetReqV1();
    }

    public static com.teneasyChat.api.core.Cache.SetReqV1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SetReqV1>
        PARSER = new com.google.protobuf.AbstractParser<SetReqV1>() {
      @java.lang.Override
      public SetReqV1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SetReqV1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SetReqV1> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.core.Cache.SetReqV1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SetRespV1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.core.SetRespV1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 key = 1;</code>
     * @return The key.
     */
    long getKey();

    /**
     * <pre>
     * 执行次数
     * </pre>
     *
     * <code>uint64 exec_num = 2;</code>
     * @return The execNum.
     */
    long getExecNum();

    /**
     * <code>uint64 value = 3;</code>
     * @return The value.
     */
    long getValue();

    /**
     * <code>uint64 value_time = 4;</code>
     * @return The valueTime.
     */
    long getValueTime();

    /**
     * <pre>
     * 执行时间
     * </pre>
     *
     * <code>int64 exec_mil_time = 5;</code>
     * @return The execMilTime.
     */
    long getExecMilTime();
  }
  /**
   * Protobuf type {@code api.core.SetRespV1}
   */
  public static final class SetRespV1 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:api.core.SetRespV1)
      SetRespV1OrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        SetRespV1.class.getName());
    }
    // Use SetRespV1.newBuilder() to construct.
    private SetRespV1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SetRespV1() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.core.Cache.internal_static_api_core_SetRespV1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.core.Cache.internal_static_api_core_SetRespV1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.core.Cache.SetRespV1.class, com.teneasyChat.api.core.Cache.SetRespV1.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private long key_ = 0L;
    /**
     * <code>uint64 key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public long getKey() {
      return key_;
    }

    public static final int EXEC_NUM_FIELD_NUMBER = 2;
    private long execNum_ = 0L;
    /**
     * <pre>
     * 执行次数
     * </pre>
     *
     * <code>uint64 exec_num = 2;</code>
     * @return The execNum.
     */
    @java.lang.Override
    public long getExecNum() {
      return execNum_;
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private long value_ = 0L;
    /**
     * <code>uint64 value = 3;</code>
     * @return The value.
     */
    @java.lang.Override
    public long getValue() {
      return value_;
    }

    public static final int VALUE_TIME_FIELD_NUMBER = 4;
    private long valueTime_ = 0L;
    /**
     * <code>uint64 value_time = 4;</code>
     * @return The valueTime.
     */
    @java.lang.Override
    public long getValueTime() {
      return valueTime_;
    }

    public static final int EXEC_MIL_TIME_FIELD_NUMBER = 5;
    private long execMilTime_ = 0L;
    /**
     * <pre>
     * 执行时间
     * </pre>
     *
     * <code>int64 exec_mil_time = 5;</code>
     * @return The execMilTime.
     */
    @java.lang.Override
    public long getExecMilTime() {
      return execMilTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (key_ != 0L) {
        output.writeUInt64(1, key_);
      }
      if (execNum_ != 0L) {
        output.writeUInt64(2, execNum_);
      }
      if (value_ != 0L) {
        output.writeUInt64(3, value_);
      }
      if (valueTime_ != 0L) {
        output.writeUInt64(4, valueTime_);
      }
      if (execMilTime_ != 0L) {
        output.writeInt64(5, execMilTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (key_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, key_);
      }
      if (execNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, execNum_);
      }
      if (value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, value_);
      }
      if (valueTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, valueTime_);
      }
      if (execMilTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, execMilTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.core.Cache.SetRespV1)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.core.Cache.SetRespV1 other = (com.teneasyChat.api.core.Cache.SetRespV1) obj;

      if (getKey()
          != other.getKey()) return false;
      if (getExecNum()
          != other.getExecNum()) return false;
      if (getValue()
          != other.getValue()) return false;
      if (getValueTime()
          != other.getValueTime()) return false;
      if (getExecMilTime()
          != other.getExecMilTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getKey());
      hash = (37 * hash) + EXEC_NUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExecNum());
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValue());
      hash = (37 * hash) + VALUE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValueTime());
      hash = (37 * hash) + EXEC_MIL_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExecMilTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.core.Cache.SetRespV1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.Cache.SetRespV1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.SetRespV1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.Cache.SetRespV1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.SetRespV1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.Cache.SetRespV1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.SetRespV1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.Cache.SetRespV1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.teneasyChat.api.core.Cache.SetRespV1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.teneasyChat.api.core.Cache.SetRespV1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.Cache.SetRespV1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.Cache.SetRespV1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.core.Cache.SetRespV1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code api.core.SetRespV1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.core.SetRespV1)
        com.teneasyChat.api.core.Cache.SetRespV1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.core.Cache.internal_static_api_core_SetRespV1_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.core.Cache.internal_static_api_core_SetRespV1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.core.Cache.SetRespV1.class, com.teneasyChat.api.core.Cache.SetRespV1.Builder.class);
      }

      // Construct using com.teneasyChat.api.core.Cache.SetRespV1.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = 0L;
        execNum_ = 0L;
        value_ = 0L;
        valueTime_ = 0L;
        execMilTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.core.Cache.internal_static_api_core_SetRespV1_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.Cache.SetRespV1 getDefaultInstanceForType() {
        return com.teneasyChat.api.core.Cache.SetRespV1.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.core.Cache.SetRespV1 build() {
        com.teneasyChat.api.core.Cache.SetRespV1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.Cache.SetRespV1 buildPartial() {
        com.teneasyChat.api.core.Cache.SetRespV1 result = new com.teneasyChat.api.core.Cache.SetRespV1(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.api.core.Cache.SetRespV1 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.execNum_ = execNum_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.valueTime_ = valueTime_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.execMilTime_ = execMilTime_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.core.Cache.SetRespV1) {
          return mergeFrom((com.teneasyChat.api.core.Cache.SetRespV1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.core.Cache.SetRespV1 other) {
        if (other == com.teneasyChat.api.core.Cache.SetRespV1.getDefaultInstance()) return this;
        if (other.getKey() != 0L) {
          setKey(other.getKey());
        }
        if (other.getExecNum() != 0L) {
          setExecNum(other.getExecNum());
        }
        if (other.getValue() != 0L) {
          setValue(other.getValue());
        }
        if (other.getValueTime() != 0L) {
          setValueTime(other.getValueTime());
        }
        if (other.getExecMilTime() != 0L) {
          setExecMilTime(other.getExecMilTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                key_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                execNum_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                value_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                valueTime_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                execMilTime_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long key_ ;
      /**
       * <code>uint64 key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public long getKey() {
        return key_;
      }
      /**
       * <code>uint64 key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(long value) {

        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = 0L;
        onChanged();
        return this;
      }

      private long execNum_ ;
      /**
       * <pre>
       * 执行次数
       * </pre>
       *
       * <code>uint64 exec_num = 2;</code>
       * @return The execNum.
       */
      @java.lang.Override
      public long getExecNum() {
        return execNum_;
      }
      /**
       * <pre>
       * 执行次数
       * </pre>
       *
       * <code>uint64 exec_num = 2;</code>
       * @param value The execNum to set.
       * @return This builder for chaining.
       */
      public Builder setExecNum(long value) {

        execNum_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 执行次数
       * </pre>
       *
       * <code>uint64 exec_num = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        execNum_ = 0L;
        onChanged();
        return this;
      }

      private long value_ ;
      /**
       * <code>uint64 value = 3;</code>
       * @return The value.
       */
      @java.lang.Override
      public long getValue() {
        return value_;
      }
      /**
       * <code>uint64 value = 3;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(long value) {

        value_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = 0L;
        onChanged();
        return this;
      }

      private long valueTime_ ;
      /**
       * <code>uint64 value_time = 4;</code>
       * @return The valueTime.
       */
      @java.lang.Override
      public long getValueTime() {
        return valueTime_;
      }
      /**
       * <code>uint64 value_time = 4;</code>
       * @param value The valueTime to set.
       * @return This builder for chaining.
       */
      public Builder setValueTime(long value) {

        valueTime_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 value_time = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearValueTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        valueTime_ = 0L;
        onChanged();
        return this;
      }

      private long execMilTime_ ;
      /**
       * <pre>
       * 执行时间
       * </pre>
       *
       * <code>int64 exec_mil_time = 5;</code>
       * @return The execMilTime.
       */
      @java.lang.Override
      public long getExecMilTime() {
        return execMilTime_;
      }
      /**
       * <pre>
       * 执行时间
       * </pre>
       *
       * <code>int64 exec_mil_time = 5;</code>
       * @param value The execMilTime to set.
       * @return This builder for chaining.
       */
      public Builder setExecMilTime(long value) {

        execMilTime_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 执行时间
       * </pre>
       *
       * <code>int64 exec_mil_time = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecMilTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        execMilTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.core.SetRespV1)
    }

    // @@protoc_insertion_point(class_scope:api.core.SetRespV1)
    private static final com.teneasyChat.api.core.Cache.SetRespV1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.core.Cache.SetRespV1();
    }

    public static com.teneasyChat.api.core.Cache.SetRespV1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SetRespV1>
        PARSER = new com.google.protobuf.AbstractParser<SetRespV1>() {
      @java.lang.Override
      public SetRespV1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SetRespV1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SetRespV1> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.core.Cache.SetRespV1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_core_GetReqV1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_core_GetReqV1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_core_GetRespV1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_core_GetRespV1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_core_SetReqV1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_core_SetReqV1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_core_SetRespV1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_core_SetRespV1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024api/core/cache.proto\022\010api.core\032\020api/op" +
      "tion.proto\032\033google/protobuf/empty.proto\032" +
      "\027validate/validate.proto\"8\n\010GetReqV1\022\013\n\003" +
      "key\030\001 \001(\004\022\020\n\010exec_num\030\002 \001(\004\022\r\n\005c_num\030\003 \001" +
      "(\004\"d\n\tGetRespV1\022\013\n\003key\030\001 \001(\004\022\020\n\010exec_num" +
      "\030\002 \001(\004\022\r\n\005value\030\003 \001(\004\022\022\n\nvalue_time\030\004 \001(" +
      "\004\022\025\n\rexec_mil_time\030\005 \001(\003\"G\n\010SetReqV1\022\013\n\003" +
      "key\030\001 \001(\004\022\r\n\005value\030\002 \001(\004\022\020\n\010exec_num\030\003 \001" +
      "(\004\022\r\n\005c_num\030\004 \001(\004\"d\n\tSetRespV1\022\013\n\003key\030\001 " +
      "\001(\004\022\020\n\010exec_num\030\002 \001(\004\022\r\n\005value\030\003 \001(\004\022\022\n\n" +
      "value_time\030\004 \001(\004\022\025\n\rexec_mil_time\030\005 \001(\0032" +
      "\265\001\n\014CacheService\022B\n\010CacheGet\022\022.api.core." +
      "GetReqV1\032\023.api.core.GetRespV1\"\r\272\276\031\t\010\260\t\322\014" +
      "\003get\022B\n\010CacheSet\022\022.api.core.SetReqV1\032\023.a" +
      "pi.core.SetRespV1\"\r\272\276\031\t\010\262\t\322\014\003set\032\035\272\276\031\031\272\006" +
      "\005cache\312\014\002\002\004\322\014\tapi/cacheBE\n\030com.teneasyCh" +
      "at.api.coreZ\021wcs/api/core;core\272\276\031\024\242\006\004jef" +
      "f\262\006\n2023-01-14b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.teneasyChat.api.Option.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
        });
    internal_static_api_core_GetReqV1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_core_GetReqV1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_core_GetReqV1_descriptor,
        new java.lang.String[] { "Key", "ExecNum", "CNum", });
    internal_static_api_core_GetRespV1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_core_GetRespV1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_core_GetRespV1_descriptor,
        new java.lang.String[] { "Key", "ExecNum", "Value", "ValueTime", "ExecMilTime", });
    internal_static_api_core_SetReqV1_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_core_SetReqV1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_core_SetReqV1_descriptor,
        new java.lang.String[] { "Key", "Value", "ExecNum", "CNum", });
    internal_static_api_core_SetRespV1_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_core_SetRespV1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_core_SetRespV1_descriptor,
        new java.lang.String[] { "Key", "ExecNum", "Value", "ValueTime", "ExecMilTime", });
    descriptor.resolveAllFeaturesImmutable();
    com.teneasyChat.api.Option.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.teneasyChat.api.Option.info);
    registry.add(com.teneasyChat.api.Option.method);
    registry.add(com.teneasyChat.api.Option.service);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
