// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/core/official_website.proto
// Protobuf Java Version: 4.26.1

package com.teneasyChat.api.core;

public final class OfficialWebsite {
  private OfficialWebsite() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      OfficialWebsite.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037api/core/official_website.proto\022\010api.c" +
      "ore\032\020api/option.proto\032\033google/protobuf/e" +
      "mpty.protoBF\n\030com.teneasyChat.api.coreZ\021" +
      "wcs/api/core;core\272\276\031\025\242\006\005baiyu\262\006\n2025-02-" +
      "18b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.teneasyChat.api.Option.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    descriptor.resolveAllFeaturesImmutable();
    com.teneasyChat.api.Option.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.teneasyChat.api.Option.info);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
