// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/c_tenant.proto
// Protobuf Java Version: 4.26.1

package com.teneasyChat.api.common;

public final class CTenant {
  private CTenant() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      CTenant.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TenantsLineGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.common.TenantsLineGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     * 线路组名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * 线路组名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * H5线路
     * </pre>
     *
     * <code>.api.common.ListString h5_lines = 3;</code>
     * @return Whether the h5Lines field is set.
     */
    boolean hasH5Lines();
    /**
     * <pre>
     * H5线路
     * </pre>
     *
     * <code>.api.common.ListString h5_lines = 3;</code>
     * @return The h5Lines.
     */
    com.teneasyChat.api.common.CBase.ListString getH5Lines();
    /**
     * <pre>
     * H5线路
     * </pre>
     *
     * <code>.api.common.ListString h5_lines = 3;</code>
     */
    com.teneasyChat.api.common.CBase.ListStringOrBuilder getH5LinesOrBuilder();

    /**
     * <pre>
     * 后台线路
     * </pre>
     *
     * <code>.api.common.ListString background_lines = 4;</code>
     * @return Whether the backgroundLines field is set.
     */
    boolean hasBackgroundLines();
    /**
     * <pre>
     * 后台线路
     * </pre>
     *
     * <code>.api.common.ListString background_lines = 4;</code>
     * @return The backgroundLines.
     */
    com.teneasyChat.api.common.CBase.ListString getBackgroundLines();
    /**
     * <pre>
     * 后台线路
     * </pre>
     *
     * <code>.api.common.ListString background_lines = 4;</code>
     */
    com.teneasyChat.api.common.CBase.ListStringOrBuilder getBackgroundLinesOrBuilder();

    /**
     * <pre>
     * 操作人
     * </pre>
     *
     * <code>int32 operate_uid = 5;</code>
     * @return The operateUid.
     */
    int getOperateUid();

    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string description = 6;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string description = 6;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_at = 7;</code>
     * @return Whether the createAt field is set.
     */
    boolean hasCreateAt();
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_at = 7;</code>
     * @return The createAt.
     */
    com.google.protobuf.Timestamp getCreateAt();
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_at = 7;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreateAtOrBuilder();

    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_at = 8;</code>
     * @return Whether the updateAt field is set.
     */
    boolean hasUpdateAt();
    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_at = 8;</code>
     * @return The updateAt.
     */
    com.google.protobuf.Timestamp getUpdateAt();
    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_at = 8;</code>
     */
    com.google.protobuf.TimestampOrBuilder getUpdateAtOrBuilder();

    /**
     * <pre>
     * 删除时间, 软删除标记
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delete_at = 9;</code>
     * @return Whether the deleteAt field is set.
     */
    boolean hasDeleteAt();
    /**
     * <pre>
     * 删除时间, 软删除标记
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delete_at = 9;</code>
     * @return The deleteAt.
     */
    com.google.protobuf.Timestamp getDeleteAt();
    /**
     * <pre>
     * 删除时间, 软删除标记
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delete_at = 9;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDeleteAtOrBuilder();

    /**
     * <pre>
     * 操作人name
     * </pre>
     *
     * <code>string operate_name = 10;</code>
     * @return The operateName.
     */
    java.lang.String getOperateName();
    /**
     * <pre>
     * 操作人name
     * </pre>
     *
     * <code>string operate_name = 10;</code>
     * @return The bytes for operateName.
     */
    com.google.protobuf.ByteString
        getOperateNameBytes();
  }
  /**
   * <pre>
   * 商户线路组
   * </pre>
   *
   * Protobuf type {@code api.common.TenantsLineGroup}
   */
  public static final class TenantsLineGroup extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:api.common.TenantsLineGroup)
      TenantsLineGroupOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        TenantsLineGroup.class.getName());
    }
    // Use TenantsLineGroup.newBuilder() to construct.
    private TenantsLineGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TenantsLineGroup() {
      name_ = "";
      description_ = "";
      operateName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.common.CTenant.internal_static_api_common_TenantsLineGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.common.CTenant.internal_static_api_common_TenantsLineGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.common.CTenant.TenantsLineGroup.class, com.teneasyChat.api.common.CTenant.TenantsLineGroup.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     * 线路组名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 线路组名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int H5_LINES_FIELD_NUMBER = 3;
    private com.teneasyChat.api.common.CBase.ListString h5Lines_;
    /**
     * <pre>
     * H5线路
     * </pre>
     *
     * <code>.api.common.ListString h5_lines = 3;</code>
     * @return Whether the h5Lines field is set.
     */
    @java.lang.Override
    public boolean hasH5Lines() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * H5线路
     * </pre>
     *
     * <code>.api.common.ListString h5_lines = 3;</code>
     * @return The h5Lines.
     */
    @java.lang.Override
    public com.teneasyChat.api.common.CBase.ListString getH5Lines() {
      return h5Lines_ == null ? com.teneasyChat.api.common.CBase.ListString.getDefaultInstance() : h5Lines_;
    }
    /**
     * <pre>
     * H5线路
     * </pre>
     *
     * <code>.api.common.ListString h5_lines = 3;</code>
     */
    @java.lang.Override
    public com.teneasyChat.api.common.CBase.ListStringOrBuilder getH5LinesOrBuilder() {
      return h5Lines_ == null ? com.teneasyChat.api.common.CBase.ListString.getDefaultInstance() : h5Lines_;
    }

    public static final int BACKGROUND_LINES_FIELD_NUMBER = 4;
    private com.teneasyChat.api.common.CBase.ListString backgroundLines_;
    /**
     * <pre>
     * 后台线路
     * </pre>
     *
     * <code>.api.common.ListString background_lines = 4;</code>
     * @return Whether the backgroundLines field is set.
     */
    @java.lang.Override
    public boolean hasBackgroundLines() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 后台线路
     * </pre>
     *
     * <code>.api.common.ListString background_lines = 4;</code>
     * @return The backgroundLines.
     */
    @java.lang.Override
    public com.teneasyChat.api.common.CBase.ListString getBackgroundLines() {
      return backgroundLines_ == null ? com.teneasyChat.api.common.CBase.ListString.getDefaultInstance() : backgroundLines_;
    }
    /**
     * <pre>
     * 后台线路
     * </pre>
     *
     * <code>.api.common.ListString background_lines = 4;</code>
     */
    @java.lang.Override
    public com.teneasyChat.api.common.CBase.ListStringOrBuilder getBackgroundLinesOrBuilder() {
      return backgroundLines_ == null ? com.teneasyChat.api.common.CBase.ListString.getDefaultInstance() : backgroundLines_;
    }

    public static final int OPERATE_UID_FIELD_NUMBER = 5;
    private int operateUid_ = 0;
    /**
     * <pre>
     * 操作人
     * </pre>
     *
     * <code>int32 operate_uid = 5;</code>
     * @return The operateUid.
     */
    @java.lang.Override
    public int getOperateUid() {
      return operateUid_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string description = 6;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string description = 6;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATE_AT_FIELD_NUMBER = 7;
    private com.google.protobuf.Timestamp createAt_;
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_at = 7;</code>
     * @return Whether the createAt field is set.
     */
    @java.lang.Override
    public boolean hasCreateAt() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_at = 7;</code>
     * @return The createAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreateAt() {
      return createAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createAt_;
    }
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_at = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCreateAtOrBuilder() {
      return createAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createAt_;
    }

    public static final int UPDATE_AT_FIELD_NUMBER = 8;
    private com.google.protobuf.Timestamp updateAt_;
    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_at = 8;</code>
     * @return Whether the updateAt field is set.
     */
    @java.lang.Override
    public boolean hasUpdateAt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_at = 8;</code>
     * @return The updateAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getUpdateAt() {
      return updateAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateAt_;
    }
    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_at = 8;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getUpdateAtOrBuilder() {
      return updateAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateAt_;
    }

    public static final int DELETE_AT_FIELD_NUMBER = 9;
    private com.google.protobuf.Timestamp deleteAt_;
    /**
     * <pre>
     * 删除时间, 软删除标记
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delete_at = 9;</code>
     * @return Whether the deleteAt field is set.
     */
    @java.lang.Override
    public boolean hasDeleteAt() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 删除时间, 软删除标记
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delete_at = 9;</code>
     * @return The deleteAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDeleteAt() {
      return deleteAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deleteAt_;
    }
    /**
     * <pre>
     * 删除时间, 软删除标记
     * </pre>
     *
     * <code>.google.protobuf.Timestamp delete_at = 9;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getDeleteAtOrBuilder() {
      return deleteAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deleteAt_;
    }

    public static final int OPERATE_NAME_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object operateName_ = "";
    /**
     * <pre>
     * 操作人name
     * </pre>
     *
     * <code>string operate_name = 10;</code>
     * @return The operateName.
     */
    @java.lang.Override
    public java.lang.String getOperateName() {
      java.lang.Object ref = operateName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operateName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 操作人name
     * </pre>
     *
     * <code>string operate_name = 10;</code>
     * @return The bytes for operateName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOperateNameBytes() {
      java.lang.Object ref = operateName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operateName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getH5Lines());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(4, getBackgroundLines());
      }
      if (operateUid_ != 0) {
        output.writeInt32(5, operateUid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, description_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(7, getCreateAt());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(8, getUpdateAt());
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeMessage(9, getDeleteAt());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(operateName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, operateName_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getH5Lines());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getBackgroundLines());
      }
      if (operateUid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, operateUid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, description_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getCreateAt());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getUpdateAt());
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getDeleteAt());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(operateName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, operateName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.common.CTenant.TenantsLineGroup)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.common.CTenant.TenantsLineGroup other = (com.teneasyChat.api.common.CTenant.TenantsLineGroup) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (hasH5Lines() != other.hasH5Lines()) return false;
      if (hasH5Lines()) {
        if (!getH5Lines()
            .equals(other.getH5Lines())) return false;
      }
      if (hasBackgroundLines() != other.hasBackgroundLines()) return false;
      if (hasBackgroundLines()) {
        if (!getBackgroundLines()
            .equals(other.getBackgroundLines())) return false;
      }
      if (getOperateUid()
          != other.getOperateUid()) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (hasCreateAt() != other.hasCreateAt()) return false;
      if (hasCreateAt()) {
        if (!getCreateAt()
            .equals(other.getCreateAt())) return false;
      }
      if (hasUpdateAt() != other.hasUpdateAt()) return false;
      if (hasUpdateAt()) {
        if (!getUpdateAt()
            .equals(other.getUpdateAt())) return false;
      }
      if (hasDeleteAt() != other.hasDeleteAt()) return false;
      if (hasDeleteAt()) {
        if (!getDeleteAt()
            .equals(other.getDeleteAt())) return false;
      }
      if (!getOperateName()
          .equals(other.getOperateName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasH5Lines()) {
        hash = (37 * hash) + H5_LINES_FIELD_NUMBER;
        hash = (53 * hash) + getH5Lines().hashCode();
      }
      if (hasBackgroundLines()) {
        hash = (37 * hash) + BACKGROUND_LINES_FIELD_NUMBER;
        hash = (53 * hash) + getBackgroundLines().hashCode();
      }
      hash = (37 * hash) + OPERATE_UID_FIELD_NUMBER;
      hash = (53 * hash) + getOperateUid();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      if (hasCreateAt()) {
        hash = (37 * hash) + CREATE_AT_FIELD_NUMBER;
        hash = (53 * hash) + getCreateAt().hashCode();
      }
      if (hasUpdateAt()) {
        hash = (37 * hash) + UPDATE_AT_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateAt().hashCode();
      }
      if (hasDeleteAt()) {
        hash = (37 * hash) + DELETE_AT_FIELD_NUMBER;
        hash = (53 * hash) + getDeleteAt().hashCode();
      }
      hash = (37 * hash) + OPERATE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getOperateName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.common.CTenant.TenantsLineGroup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.common.CTenant.TenantsLineGroup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CTenant.TenantsLineGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.common.CTenant.TenantsLineGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CTenant.TenantsLineGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.common.CTenant.TenantsLineGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CTenant.TenantsLineGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.common.CTenant.TenantsLineGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.teneasyChat.api.common.CTenant.TenantsLineGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.teneasyChat.api.common.CTenant.TenantsLineGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CTenant.TenantsLineGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.common.CTenant.TenantsLineGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.common.CTenant.TenantsLineGroup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 商户线路组
     * </pre>
     *
     * Protobuf type {@code api.common.TenantsLineGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.common.TenantsLineGroup)
        com.teneasyChat.api.common.CTenant.TenantsLineGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.common.CTenant.internal_static_api_common_TenantsLineGroup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.common.CTenant.internal_static_api_common_TenantsLineGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.common.CTenant.TenantsLineGroup.class, com.teneasyChat.api.common.CTenant.TenantsLineGroup.Builder.class);
      }

      // Construct using com.teneasyChat.api.common.CTenant.TenantsLineGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getH5LinesFieldBuilder();
          getBackgroundLinesFieldBuilder();
          getCreateAtFieldBuilder();
          getUpdateAtFieldBuilder();
          getDeleteAtFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        h5Lines_ = null;
        if (h5LinesBuilder_ != null) {
          h5LinesBuilder_.dispose();
          h5LinesBuilder_ = null;
        }
        backgroundLines_ = null;
        if (backgroundLinesBuilder_ != null) {
          backgroundLinesBuilder_.dispose();
          backgroundLinesBuilder_ = null;
        }
        operateUid_ = 0;
        description_ = "";
        createAt_ = null;
        if (createAtBuilder_ != null) {
          createAtBuilder_.dispose();
          createAtBuilder_ = null;
        }
        updateAt_ = null;
        if (updateAtBuilder_ != null) {
          updateAtBuilder_.dispose();
          updateAtBuilder_ = null;
        }
        deleteAt_ = null;
        if (deleteAtBuilder_ != null) {
          deleteAtBuilder_.dispose();
          deleteAtBuilder_ = null;
        }
        operateName_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.common.CTenant.internal_static_api_common_TenantsLineGroup_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.common.CTenant.TenantsLineGroup getDefaultInstanceForType() {
        return com.teneasyChat.api.common.CTenant.TenantsLineGroup.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.common.CTenant.TenantsLineGroup build() {
        com.teneasyChat.api.common.CTenant.TenantsLineGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.common.CTenant.TenantsLineGroup buildPartial() {
        com.teneasyChat.api.common.CTenant.TenantsLineGroup result = new com.teneasyChat.api.common.CTenant.TenantsLineGroup(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.api.common.CTenant.TenantsLineGroup result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.h5Lines_ = h5LinesBuilder_ == null
              ? h5Lines_
              : h5LinesBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.backgroundLines_ = backgroundLinesBuilder_ == null
              ? backgroundLines_
              : backgroundLinesBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.operateUid_ = operateUid_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.description_ = description_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.createAt_ = createAtBuilder_ == null
              ? createAt_
              : createAtBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.updateAt_ = updateAtBuilder_ == null
              ? updateAt_
              : updateAtBuilder_.build();
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.deleteAt_ = deleteAtBuilder_ == null
              ? deleteAt_
              : deleteAtBuilder_.build();
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.operateName_ = operateName_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.common.CTenant.TenantsLineGroup) {
          return mergeFrom((com.teneasyChat.api.common.CTenant.TenantsLineGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.common.CTenant.TenantsLineGroup other) {
        if (other == com.teneasyChat.api.common.CTenant.TenantsLineGroup.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasH5Lines()) {
          mergeH5Lines(other.getH5Lines());
        }
        if (other.hasBackgroundLines()) {
          mergeBackgroundLines(other.getBackgroundLines());
        }
        if (other.getOperateUid() != 0) {
          setOperateUid(other.getOperateUid());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.hasCreateAt()) {
          mergeCreateAt(other.getCreateAt());
        }
        if (other.hasUpdateAt()) {
          mergeUpdateAt(other.getUpdateAt());
        }
        if (other.hasDeleteAt()) {
          mergeDeleteAt(other.getDeleteAt());
        }
        if (!other.getOperateName().isEmpty()) {
          operateName_ = other.operateName_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getH5LinesFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getBackgroundLinesFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                operateUid_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                input.readMessage(
                    getCreateAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                input.readMessage(
                    getUpdateAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                input.readMessage(
                    getDeleteAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                operateName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 线路组名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 线路组名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 线路组名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 线路组名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 线路组名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.teneasyChat.api.common.CBase.ListString h5Lines_;
      private com.google.protobuf.SingleFieldBuilder<
          com.teneasyChat.api.common.CBase.ListString, com.teneasyChat.api.common.CBase.ListString.Builder, com.teneasyChat.api.common.CBase.ListStringOrBuilder> h5LinesBuilder_;
      /**
       * <pre>
       * H5线路
       * </pre>
       *
       * <code>.api.common.ListString h5_lines = 3;</code>
       * @return Whether the h5Lines field is set.
       */
      public boolean hasH5Lines() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * H5线路
       * </pre>
       *
       * <code>.api.common.ListString h5_lines = 3;</code>
       * @return The h5Lines.
       */
      public com.teneasyChat.api.common.CBase.ListString getH5Lines() {
        if (h5LinesBuilder_ == null) {
          return h5Lines_ == null ? com.teneasyChat.api.common.CBase.ListString.getDefaultInstance() : h5Lines_;
        } else {
          return h5LinesBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * H5线路
       * </pre>
       *
       * <code>.api.common.ListString h5_lines = 3;</code>
       */
      public Builder setH5Lines(com.teneasyChat.api.common.CBase.ListString value) {
        if (h5LinesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          h5Lines_ = value;
        } else {
          h5LinesBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * H5线路
       * </pre>
       *
       * <code>.api.common.ListString h5_lines = 3;</code>
       */
      public Builder setH5Lines(
          com.teneasyChat.api.common.CBase.ListString.Builder builderForValue) {
        if (h5LinesBuilder_ == null) {
          h5Lines_ = builderForValue.build();
        } else {
          h5LinesBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * H5线路
       * </pre>
       *
       * <code>.api.common.ListString h5_lines = 3;</code>
       */
      public Builder mergeH5Lines(com.teneasyChat.api.common.CBase.ListString value) {
        if (h5LinesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            h5Lines_ != null &&
            h5Lines_ != com.teneasyChat.api.common.CBase.ListString.getDefaultInstance()) {
            getH5LinesBuilder().mergeFrom(value);
          } else {
            h5Lines_ = value;
          }
        } else {
          h5LinesBuilder_.mergeFrom(value);
        }
        if (h5Lines_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * H5线路
       * </pre>
       *
       * <code>.api.common.ListString h5_lines = 3;</code>
       */
      public Builder clearH5Lines() {
        bitField0_ = (bitField0_ & ~0x00000004);
        h5Lines_ = null;
        if (h5LinesBuilder_ != null) {
          h5LinesBuilder_.dispose();
          h5LinesBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * H5线路
       * </pre>
       *
       * <code>.api.common.ListString h5_lines = 3;</code>
       */
      public com.teneasyChat.api.common.CBase.ListString.Builder getH5LinesBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getH5LinesFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * H5线路
       * </pre>
       *
       * <code>.api.common.ListString h5_lines = 3;</code>
       */
      public com.teneasyChat.api.common.CBase.ListStringOrBuilder getH5LinesOrBuilder() {
        if (h5LinesBuilder_ != null) {
          return h5LinesBuilder_.getMessageOrBuilder();
        } else {
          return h5Lines_ == null ?
              com.teneasyChat.api.common.CBase.ListString.getDefaultInstance() : h5Lines_;
        }
      }
      /**
       * <pre>
       * H5线路
       * </pre>
       *
       * <code>.api.common.ListString h5_lines = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.teneasyChat.api.common.CBase.ListString, com.teneasyChat.api.common.CBase.ListString.Builder, com.teneasyChat.api.common.CBase.ListStringOrBuilder> 
          getH5LinesFieldBuilder() {
        if (h5LinesBuilder_ == null) {
          h5LinesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.teneasyChat.api.common.CBase.ListString, com.teneasyChat.api.common.CBase.ListString.Builder, com.teneasyChat.api.common.CBase.ListStringOrBuilder>(
                  getH5Lines(),
                  getParentForChildren(),
                  isClean());
          h5Lines_ = null;
        }
        return h5LinesBuilder_;
      }

      private com.teneasyChat.api.common.CBase.ListString backgroundLines_;
      private com.google.protobuf.SingleFieldBuilder<
          com.teneasyChat.api.common.CBase.ListString, com.teneasyChat.api.common.CBase.ListString.Builder, com.teneasyChat.api.common.CBase.ListStringOrBuilder> backgroundLinesBuilder_;
      /**
       * <pre>
       * 后台线路
       * </pre>
       *
       * <code>.api.common.ListString background_lines = 4;</code>
       * @return Whether the backgroundLines field is set.
       */
      public boolean hasBackgroundLines() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 后台线路
       * </pre>
       *
       * <code>.api.common.ListString background_lines = 4;</code>
       * @return The backgroundLines.
       */
      public com.teneasyChat.api.common.CBase.ListString getBackgroundLines() {
        if (backgroundLinesBuilder_ == null) {
          return backgroundLines_ == null ? com.teneasyChat.api.common.CBase.ListString.getDefaultInstance() : backgroundLines_;
        } else {
          return backgroundLinesBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 后台线路
       * </pre>
       *
       * <code>.api.common.ListString background_lines = 4;</code>
       */
      public Builder setBackgroundLines(com.teneasyChat.api.common.CBase.ListString value) {
        if (backgroundLinesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          backgroundLines_ = value;
        } else {
          backgroundLinesBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 后台线路
       * </pre>
       *
       * <code>.api.common.ListString background_lines = 4;</code>
       */
      public Builder setBackgroundLines(
          com.teneasyChat.api.common.CBase.ListString.Builder builderForValue) {
        if (backgroundLinesBuilder_ == null) {
          backgroundLines_ = builderForValue.build();
        } else {
          backgroundLinesBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 后台线路
       * </pre>
       *
       * <code>.api.common.ListString background_lines = 4;</code>
       */
      public Builder mergeBackgroundLines(com.teneasyChat.api.common.CBase.ListString value) {
        if (backgroundLinesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            backgroundLines_ != null &&
            backgroundLines_ != com.teneasyChat.api.common.CBase.ListString.getDefaultInstance()) {
            getBackgroundLinesBuilder().mergeFrom(value);
          } else {
            backgroundLines_ = value;
          }
        } else {
          backgroundLinesBuilder_.mergeFrom(value);
        }
        if (backgroundLines_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * 后台线路
       * </pre>
       *
       * <code>.api.common.ListString background_lines = 4;</code>
       */
      public Builder clearBackgroundLines() {
        bitField0_ = (bitField0_ & ~0x00000008);
        backgroundLines_ = null;
        if (backgroundLinesBuilder_ != null) {
          backgroundLinesBuilder_.dispose();
          backgroundLinesBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 后台线路
       * </pre>
       *
       * <code>.api.common.ListString background_lines = 4;</code>
       */
      public com.teneasyChat.api.common.CBase.ListString.Builder getBackgroundLinesBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getBackgroundLinesFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 后台线路
       * </pre>
       *
       * <code>.api.common.ListString background_lines = 4;</code>
       */
      public com.teneasyChat.api.common.CBase.ListStringOrBuilder getBackgroundLinesOrBuilder() {
        if (backgroundLinesBuilder_ != null) {
          return backgroundLinesBuilder_.getMessageOrBuilder();
        } else {
          return backgroundLines_ == null ?
              com.teneasyChat.api.common.CBase.ListString.getDefaultInstance() : backgroundLines_;
        }
      }
      /**
       * <pre>
       * 后台线路
       * </pre>
       *
       * <code>.api.common.ListString background_lines = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.teneasyChat.api.common.CBase.ListString, com.teneasyChat.api.common.CBase.ListString.Builder, com.teneasyChat.api.common.CBase.ListStringOrBuilder> 
          getBackgroundLinesFieldBuilder() {
        if (backgroundLinesBuilder_ == null) {
          backgroundLinesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.teneasyChat.api.common.CBase.ListString, com.teneasyChat.api.common.CBase.ListString.Builder, com.teneasyChat.api.common.CBase.ListStringOrBuilder>(
                  getBackgroundLines(),
                  getParentForChildren(),
                  isClean());
          backgroundLines_ = null;
        }
        return backgroundLinesBuilder_;
      }

      private int operateUid_ ;
      /**
       * <pre>
       * 操作人
       * </pre>
       *
       * <code>int32 operate_uid = 5;</code>
       * @return The operateUid.
       */
      @java.lang.Override
      public int getOperateUid() {
        return operateUid_;
      }
      /**
       * <pre>
       * 操作人
       * </pre>
       *
       * <code>int32 operate_uid = 5;</code>
       * @param value The operateUid to set.
       * @return This builder for chaining.
       */
      public Builder setOperateUid(int value) {

        operateUid_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作人
       * </pre>
       *
       * <code>int32 operate_uid = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperateUid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        operateUid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string description = 6;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string description = 6;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string description = 6;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string description = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string description = 6;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp createAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createAtBuilder_;
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp create_at = 7;</code>
       * @return Whether the createAt field is set.
       */
      public boolean hasCreateAt() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp create_at = 7;</code>
       * @return The createAt.
       */
      public com.google.protobuf.Timestamp getCreateAt() {
        if (createAtBuilder_ == null) {
          return createAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createAt_;
        } else {
          return createAtBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp create_at = 7;</code>
       */
      public Builder setCreateAt(com.google.protobuf.Timestamp value) {
        if (createAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createAt_ = value;
        } else {
          createAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp create_at = 7;</code>
       */
      public Builder setCreateAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createAtBuilder_ == null) {
          createAt_ = builderForValue.build();
        } else {
          createAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp create_at = 7;</code>
       */
      public Builder mergeCreateAt(com.google.protobuf.Timestamp value) {
        if (createAtBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            createAt_ != null &&
            createAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getCreateAtBuilder().mergeFrom(value);
          } else {
            createAt_ = value;
          }
        } else {
          createAtBuilder_.mergeFrom(value);
        }
        if (createAt_ != null) {
          bitField0_ |= 0x00000040;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp create_at = 7;</code>
       */
      public Builder clearCreateAt() {
        bitField0_ = (bitField0_ & ~0x00000040);
        createAt_ = null;
        if (createAtBuilder_ != null) {
          createAtBuilder_.dispose();
          createAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp create_at = 7;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreateAtBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getCreateAtFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp create_at = 7;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreateAtOrBuilder() {
        if (createAtBuilder_ != null) {
          return createAtBuilder_.getMessageOrBuilder();
        } else {
          return createAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createAt_;
        }
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp create_at = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreateAtFieldBuilder() {
        if (createAtBuilder_ == null) {
          createAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreateAt(),
                  getParentForChildren(),
                  isClean());
          createAt_ = null;
        }
        return createAtBuilder_;
      }

      private com.google.protobuf.Timestamp updateAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updateAtBuilder_;
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp update_at = 8;</code>
       * @return Whether the updateAt field is set.
       */
      public boolean hasUpdateAt() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp update_at = 8;</code>
       * @return The updateAt.
       */
      public com.google.protobuf.Timestamp getUpdateAt() {
        if (updateAtBuilder_ == null) {
          return updateAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateAt_;
        } else {
          return updateAtBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp update_at = 8;</code>
       */
      public Builder setUpdateAt(com.google.protobuf.Timestamp value) {
        if (updateAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updateAt_ = value;
        } else {
          updateAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp update_at = 8;</code>
       */
      public Builder setUpdateAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (updateAtBuilder_ == null) {
          updateAt_ = builderForValue.build();
        } else {
          updateAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp update_at = 8;</code>
       */
      public Builder mergeUpdateAt(com.google.protobuf.Timestamp value) {
        if (updateAtBuilder_ == null) {
          if (((bitField0_ & 0x00000080) != 0) &&
            updateAt_ != null &&
            updateAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getUpdateAtBuilder().mergeFrom(value);
          } else {
            updateAt_ = value;
          }
        } else {
          updateAtBuilder_.mergeFrom(value);
        }
        if (updateAt_ != null) {
          bitField0_ |= 0x00000080;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp update_at = 8;</code>
       */
      public Builder clearUpdateAt() {
        bitField0_ = (bitField0_ & ~0x00000080);
        updateAt_ = null;
        if (updateAtBuilder_ != null) {
          updateAtBuilder_.dispose();
          updateAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp update_at = 8;</code>
       */
      public com.google.protobuf.Timestamp.Builder getUpdateAtBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getUpdateAtFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp update_at = 8;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getUpdateAtOrBuilder() {
        if (updateAtBuilder_ != null) {
          return updateAtBuilder_.getMessageOrBuilder();
        } else {
          return updateAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : updateAt_;
        }
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp update_at = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getUpdateAtFieldBuilder() {
        if (updateAtBuilder_ == null) {
          updateAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getUpdateAt(),
                  getParentForChildren(),
                  isClean());
          updateAt_ = null;
        }
        return updateAtBuilder_;
      }

      private com.google.protobuf.Timestamp deleteAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> deleteAtBuilder_;
      /**
       * <pre>
       * 删除时间, 软删除标记
       * </pre>
       *
       * <code>.google.protobuf.Timestamp delete_at = 9;</code>
       * @return Whether the deleteAt field is set.
       */
      public boolean hasDeleteAt() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <pre>
       * 删除时间, 软删除标记
       * </pre>
       *
       * <code>.google.protobuf.Timestamp delete_at = 9;</code>
       * @return The deleteAt.
       */
      public com.google.protobuf.Timestamp getDeleteAt() {
        if (deleteAtBuilder_ == null) {
          return deleteAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deleteAt_;
        } else {
          return deleteAtBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 删除时间, 软删除标记
       * </pre>
       *
       * <code>.google.protobuf.Timestamp delete_at = 9;</code>
       */
      public Builder setDeleteAt(com.google.protobuf.Timestamp value) {
        if (deleteAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deleteAt_ = value;
        } else {
          deleteAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 删除时间, 软删除标记
       * </pre>
       *
       * <code>.google.protobuf.Timestamp delete_at = 9;</code>
       */
      public Builder setDeleteAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (deleteAtBuilder_ == null) {
          deleteAt_ = builderForValue.build();
        } else {
          deleteAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 删除时间, 软删除标记
       * </pre>
       *
       * <code>.google.protobuf.Timestamp delete_at = 9;</code>
       */
      public Builder mergeDeleteAt(com.google.protobuf.Timestamp value) {
        if (deleteAtBuilder_ == null) {
          if (((bitField0_ & 0x00000100) != 0) &&
            deleteAt_ != null &&
            deleteAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getDeleteAtBuilder().mergeFrom(value);
          } else {
            deleteAt_ = value;
          }
        } else {
          deleteAtBuilder_.mergeFrom(value);
        }
        if (deleteAt_ != null) {
          bitField0_ |= 0x00000100;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * 删除时间, 软删除标记
       * </pre>
       *
       * <code>.google.protobuf.Timestamp delete_at = 9;</code>
       */
      public Builder clearDeleteAt() {
        bitField0_ = (bitField0_ & ~0x00000100);
        deleteAt_ = null;
        if (deleteAtBuilder_ != null) {
          deleteAtBuilder_.dispose();
          deleteAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 删除时间, 软删除标记
       * </pre>
       *
       * <code>.google.protobuf.Timestamp delete_at = 9;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDeleteAtBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getDeleteAtFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 删除时间, 软删除标记
       * </pre>
       *
       * <code>.google.protobuf.Timestamp delete_at = 9;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDeleteAtOrBuilder() {
        if (deleteAtBuilder_ != null) {
          return deleteAtBuilder_.getMessageOrBuilder();
        } else {
          return deleteAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : deleteAt_;
        }
      }
      /**
       * <pre>
       * 删除时间, 软删除标记
       * </pre>
       *
       * <code>.google.protobuf.Timestamp delete_at = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDeleteAtFieldBuilder() {
        if (deleteAtBuilder_ == null) {
          deleteAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDeleteAt(),
                  getParentForChildren(),
                  isClean());
          deleteAt_ = null;
        }
        return deleteAtBuilder_;
      }

      private java.lang.Object operateName_ = "";
      /**
       * <pre>
       * 操作人name
       * </pre>
       *
       * <code>string operate_name = 10;</code>
       * @return The operateName.
       */
      public java.lang.String getOperateName() {
        java.lang.Object ref = operateName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operateName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 操作人name
       * </pre>
       *
       * <code>string operate_name = 10;</code>
       * @return The bytes for operateName.
       */
      public com.google.protobuf.ByteString
          getOperateNameBytes() {
        java.lang.Object ref = operateName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operateName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 操作人name
       * </pre>
       *
       * <code>string operate_name = 10;</code>
       * @param value The operateName to set.
       * @return This builder for chaining.
       */
      public Builder setOperateName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        operateName_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作人name
       * </pre>
       *
       * <code>string operate_name = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperateName() {
        operateName_ = getDefaultInstance().getOperateName();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作人name
       * </pre>
       *
       * <code>string operate_name = 10;</code>
       * @param value The bytes for operateName to set.
       * @return This builder for chaining.
       */
      public Builder setOperateNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        operateName_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.common.TenantsLineGroup)
    }

    // @@protoc_insertion_point(class_scope:api.common.TenantsLineGroup)
    private static final com.teneasyChat.api.common.CTenant.TenantsLineGroup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.common.CTenant.TenantsLineGroup();
    }

    public static com.teneasyChat.api.common.CTenant.TenantsLineGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TenantsLineGroup>
        PARSER = new com.google.protobuf.AbstractParser<TenantsLineGroup>() {
      @java.lang.Override
      public TenantsLineGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TenantsLineGroup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TenantsLineGroup> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.common.CTenant.TenantsLineGroup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_common_TenantsLineGroup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_common_TenantsLineGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031api/common/c_tenant.proto\022\napi.common\032" +
      "\027api/common/c_base.proto\032\027validate/valid" +
      "ate.proto\032\037google/protobuf/timestamp.pro" +
      "to\"\325\002\n\020TenantsLineGroup\022\n\n\002id\030\001 \001(\005\022\014\n\004n" +
      "ame\030\002 \001(\t\022(\n\010h5_lines\030\003 \001(\0132\026.api.common" +
      ".ListString\0220\n\020background_lines\030\004 \001(\0132\026." +
      "api.common.ListString\022\023\n\013operate_uid\030\005 \001" +
      "(\005\022\023\n\013description\030\006 \001(\t\022-\n\tcreate_at\030\007 \001" +
      "(\0132\032.google.protobuf.Timestamp\022-\n\tupdate" +
      "_at\030\010 \001(\0132\032.google.protobuf.Timestamp\022-\n" +
      "\tdelete_at\030\t \001(\0132\032.google.protobuf.Times" +
      "tamp\022\024\n\014operate_name\030\n \001(\tB3\n\032com.teneas" +
      "yChat.api.commonZ\025wcs/api/common;commonb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.teneasyChat.api.common.CBase.getDescriptor(),
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_api_common_TenantsLineGroup_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_common_TenantsLineGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_common_TenantsLineGroup_descriptor,
        new java.lang.String[] { "Id", "Name", "H5Lines", "BackgroundLines", "OperateUid", "Description", "CreateAt", "UpdateAt", "DeleteAt", "OperateName", });
    descriptor.resolveAllFeaturesImmutable();
    com.teneasyChat.api.common.CBase.getDescriptor();
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
